name: Python 3.8
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make install
      working-directory: |
        "Course 1 Cloud Computing Foundations/Week 3/scaffold"
    - name: Lint with Pylint
      run: |
        make lint
      working-directory: |
        "Course 1 Cloud Computing Foundations/Week 3/scaffold"
    - name: Test with Pytest
      run: |
        make test
      working-directory: |
        "Course 1 Cloud Computing Foundations/Week 3/scaffold"
    - name: Format code with Python black
      run: |
        make format
      working-directory: |
        "Course 1 Cloud Computing Foundations/Week 3/scaffold"
